name: hexlet-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hexlet project check
        uses: hexlet/project-action@release
        with:
          hexlet-id: ${{ secrets.HEXLET_ID }}

      - name: Upload test artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: tmp/artifacts
